### ISSUE TITLE
When I log in to the server, I get this error and the scoreboard is not shown

### ISSUE THREAD

**Issue by anhead** [TheIndra55/SpigotBoard#1]
22:00:30 [SEVERE] Could not pass event PlayerJoinEvent to SpigotBoard v1.0.2
22:00:30 org.bukkit.event.EventException
22:00:30 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:31 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:815) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:32 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:32 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:32 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:32 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:32 Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:32 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:32 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:32 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:32 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:32 	at nl.theindra.krille.scoreboard.Main.onJoin(Main.java:128) ~[?:?]
22:00:32 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
22:00:32 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
22:00:32 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
22:00:32 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
22:00:32 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:32 	... 14 more
22:00:32 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:32 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:32 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:33 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:33 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:33 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:33 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:33 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:33 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:33 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:33 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:33 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:33 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:33 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:33 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:33 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:33 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:34 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:34 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:34 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:34 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:34 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:34 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:34 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:34 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:34 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:34 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:34 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:34 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:34 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:34 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:34 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:34 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:34 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:35 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:35 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:35 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:35 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:35 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:35 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:35 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:35 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:35 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
22:00:36 [WARNING] [SpigotBoard] Task #4 for SpigotBoard v1.0.2 generated an exception
22:00:36 java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22:00:36 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
22:00:36 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
22:00:36 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
22:00:36 	at nl.theindra.krille.scoreboard.Main.Addscoreboard(Main.java:98) ~[?:?]
22:00:36 	at nl.theindra.krille.scoreboard.Main$1.run(Main.java:137) ~[?:?]
22:00:36 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-7d15d07-c194444]
22:00:36 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by TheIndra55** [comment]
Are you using vault? If your using vault are you sure your using a group plugin and balance?

**Comment by anhead** [comment]
Yes that was the problem now it works thanks
