### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ReDcTiOn** [TheIndra55/SpigotBoard#2]
Error: http://pastebin.com/p3q52HBw

**Comment by TheIndra55** [comment]
Did this happen when you typed /spigotboard version, I think my website was down. Spigotboard uses some scripts of my website ;)

**Comment by ReDcTiOn** [comment]
No, do not enter anything, still plugin an error.

Sorry for my English.

**Comment by TheIndra55** [comment]
Looks like my website is blocking your server...

**Comment by ReDcTiOn** [comment]
46.174.48.113 ip my server

**Comment by TheIndra55** [comment]
You send me not your proxy ip, So i cant join

**Comment by TheIndra55** [comment]
Im banned from your proxy, Because i did the chaptcha wrong

**Comment by ReDcTiOn** [comment]
Only today has changed, keep: 212.22.93.203

**Comment by TheIndra55** [comment]
Try the new version! 1.0.4

**Comment by ReDcTiOn** [comment]
Everything is working. Thank you! ;)

**Comment by ReDcTiOn** [comment]
Make the variables:
- Region WorldGuard. {wg_regionname}

Thanks :)

P.S. This variable has been implemented in the plugin InfoBoardReborn, but the plugin is not updated :(
