### ISSUE TITLE
Flicker problem

### ISSUE THREAD

**Issue by HORTEXX** [TheIndra55/SpigotBoard#2]
Hello.
I have a problem with this plug. After uploading it to the Spigotboard server it flashes extremely badly. How to fix it ?

**Comment by yPedx** [comment]
Could you make a video to show what's happening? I haven't experienced this before at all.

**Comment by HORTEXX** [comment]
Link to movie
https://www.youtube.com/watch?v=Ztjq_Q5T_Js&feature=youtu.be
There is a problem with the hours

**Comment by TheIndra55** [comment]
@HORTEXX Video is not avaible

**Comment by HORTEXX** [comment]
sorry
https://www.youtube.com/watch?v=Ztjq_Q5T_Js

**Comment by yPedx** [comment]
The flickering? It's the scoreboard updating

**Comment by HORTEXX** [comment]
And you can do something about it ?
I also show the wrong hour, It's 30-60 minutes late.

**Comment by TheIndra55** [comment]
@HORTEXX If the time on the board is wrong it's probably because your host is in another timezone as you

**Comment by yPedx** [comment]
I'll be working on a timezone based calendar.
And for the flickering, how much TPS does your server have? I still don't experience any flickering for me (1gb RAM)

**Comment by HORTEXX** [comment]
TPS 20
8 GB RAM
