### ISSUE TITLE
Incompatible with Citizens Plugin

### ISSUE THREAD

**Issue by blackphreak** [TheIndra55/SpigotBoard#3]
When your plugin is loaded, it will override the Citizens (NPC Teams), which makes Citizens do not show the npc name anymore until I disable your plugin and reload Citizens (in order to regenerate those NPCs).

When I enable your plugin again, it start to override the NPC name again...so, please fix this, thx.

I don't know if this works or not, but I think you can try to fix the bug with this:
- use :
        Bukkit.getServer().getScoreboardManager().getMainScoreboard();
  to replace this :
        Bukkit.getServer().getScoreboardManager().getNewScoreboard();

Spigot Version: 1.12-R0.1-SNAPSHOT
Ref.: https://github.com/CitizensDev/Citizens2/blob/81457511369ed332209dd73ad033a19ca565b810/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/entity/HumanController.java

**Comment by TheIndra55** [comment]
I discontinued this project, ypedx continued it here https://www.spigotmc.org/resources/spigotboard.47497/
Also
