### ISSUE TITLE
Issue Health2

### ISSUE THREAD

**Issue by yerbuky** [TheIndra55/SpigotBoard#4]
2:12:34 CONSOLE: WARN]: [SpigotBoard] Task #25 for SpigotBoard v1.0.4 generated an exception
2:12:34 CONSOLE: Source) ~[?:1.8.0_45]
2:12:34 CONSOLE: Source) [?:1.8.0_45]

When i have only middle heart, the scoreboard disappear and it generate a Warn in console.

Cuando tengo solo medio corazón, el scoreboard desaparece y genera un error.

title: '&f@&b&lTierra&b&lMine_MoDs'

text:
     - '   {Health2}'
     - 'Nick: &a{Name}'
     - 'Rango: &6{Group}'
     - 'Hora: &7{Time}'
     - '&r'
     - 'Dinero: &e{Money}'
     - 'Online: &a{Online}&7/&c{MaxPlayers}'
     - 'Ping: &a{Ping}'
     - '  &7{Coords}'

**Comment by TheIndra55** [comment]
What version is your server ?

**Comment by yerbuky** [comment]
Craftbukkit.1.9.2-snapshot.r01 its date is on 9th April 2016.

**Comment by yerbuky** [comment]
This server is running CraftBukkit version git-Bukkit-8cb1b36 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by TheIndra55** [comment]
Ok, What version of spigotboard?
