### ISSUE TITLE
i dont see the scoreboard

### ISSUE THREAD

**Issue by Ghandidcm** [TheIndra55/SpigotBoard#6]
Hello, i don't see the scoreboard. Must you enable the worlds or not?

[Photo 1](https://lh3.googleusercontent.com/2uWKg0p4ICvRr69MptpVgo19VSUU7y_vIXQSsKA47CTMwxLqdNKwW5-R2oBW5KyADfq6=s170)
[Photo 2](https://lh3.googleusercontent.com/G-ZdXQ1lew6mfaIS9ul1dwZ36mj6d1ALmpFVQgb8SzayReR0gd5qacuTw9_RA8b5v4fk=s170)
[Photo 3](https://lh3.googleusercontent.com/fCed078tPFX8IdsB8mrTj4qymHXaXBG69PgGo545WU4pqqr0B_d_BJy5UK1YhbFYTgvt=s159)
[Photo 4:](https://lh3.googleusercontent.com/vNR25Alubhk8o2PDx3qmSmthvt5nDq1H7tvBJjZAOMoQOoCLFYm0_5RomX7AvkdCb-TK6Q=s162)
[Photo 5:](https://lh3.googleusercontent.com/iRdXVrkwA9llD1mFVd5v8oSvjDJM3xtGYii3XZGBm4AUIGmWinfTuzAm6g2jAOZMuARddw=s158)

(Sorry for the small photos)

**Comment by TheIndra55** [comment]
Can you please send bigger photos.

**Comment by Ghandidcm** [comment]
Save the photos and open them...

**Comment by TheIndra55** [comment]
I dont have the permission to view them
